-- BUNU DENEMISTIM, CALISMADI YA DA ISTEDIGIM SONUCU VERMEDI 
CREATE TABLE IF NOT EXISTS MAIN_DATA_LOG (
	timestamp TEXT,
	operation TEXT,
	row_id INTEGER,
	old_data TEXT,
	new_data TEXT
);


DROP TRIGGER IF EXISTS MAIN_DATA_UPDATE_TRIGGER;
CREATE TRIGGER IF NOT EXISTS MAIN_DATA_UPDATE_TRIGGER
AFTER UPDATE ON MAIN_DATA
BEGIN
    INSERT INTO MAIN_DATA_LOG (timestamp, operation, row_id, old_data, new_data)
    VALUES (datetime('now'), 'UPDATE', NEW.rowid, json(OLD), json(NEW));
END;


