-- GOOGLE SHEET DATA SAYFASININ AKTARILMASI
INSERT INTO EPISODES
 (ID, RELATED_ID, EPISODE_NO, EPISODE_NAME, INSERT_DATE, UPDATE_DATE, WATCHED_DATE)

SELECT AUTO_ID
		,RELATED_ID
		,EPISODE_NO
		,EPISODE_NAME
		,CASE WHEN INSERT_DATE IS NULL THEN "1900-01-01" ELSE substr(INSERT_DATE,7,4) || '-' || substr(INSERT_DATE,4,2) || '-' || substr(INSERT_DATE,1,2) END AS INSERT_DATE_NEW
		,CASE WHEN UPDATE_DATE IS NULL THEN "1900-01-01" ELSE substr(UPDATE_DATE,7,4) || '-' || substr(UPDATE_DATE,4,2) || '-' || substr(UPDATE_DATE,1,2) END AS UPDATE_DATE_NEW
		,CASE WHEN WATCHED_DATE IS NULL THEN "1900-01-01" ELSE substr(WATCHED_DATE,7,4) || '-' || substr(WATCHED_DATE,4,2) || '-' || substr(WATCHED_DATE,1,2) END AS WATCHED_DATE_NEW	
FROM GOOGLE_SHEETS_EPISODES